import { FabricContext, FabricUdf, DataConnection, FabricSqlConnection } from "../fabric/udf";
import { PersonDto } from "../sharedTypes/person";
import { Todo } from "../sharedTypes/todo";

import { RayfinFunctionSchema } from "../rayfin/functions";

// Fabric UDFs

const udf = new FabricUdf();

// Define Data Connections to share across functions. 
const myTodoDbConn = new DataConnection("myTodoDb", "myTodoDbConn");


// Functions Can Be Defined in different ways:

// 1. With generic argument, we attempt to parse the request to that type.
udf.func<Todo>("addTodo", async (todo: Todo, myTodoDbConn: FabricSqlConnection) => {
    
    // Logic to add the todo item to a database or in-memory store
    console.log(`Adding todo: ${todo.title}`);
    // myTodoDbConn.sql("INSERT INTO todos (title, completed) VALUES (?, ?)", [todo.title, todo.completed]);

    return { success: true, message: `Todo '${todo.title}' added successfully!` };
}, [myTodoDbConn]);
/*
Metadata for function generated by AST Parser
- "addTodo" (fabric.ts)
  Async: true, Has Data Connections: true
  Generic Type: <Todo>
    Type Structure:
      id: number
      title: string
      completed: boolean
  Parameters:
    Position 0: todo: Todo
    Position 1: myTodoDbConn: FabricSqlConnection [FABRIC: FabricSqlConnection]
  Parameter Summary:
    Total Parameters: 2
    Fabric Parameters: 1
      Position 1: myTodoDbConn (FabricSqlConnection)
    Business Parameters: 1
      Position 0: todo: Todo
  ✅ Parameter validation: All parameters match generic type structure
*/


// 2. With generic argument and spread parameters. This allows for more traditional parameter passing.
udf.func<Todo>("addTodoSpreadParams", async (id: number, title: string, completed: boolean, myTodoDbConn: FabricSqlConnection) => {
    // Logic to add the todo item to a database or in-memory store
    console.log(`Adding todo: ${title}`);
    return { success: true, message: `Todo '${title}' added successfully!` };

}, [myTodoDbConn]);
/*
"addTodoSpreadParams" (fabric.ts)
  Async: true, Has Data Connections: true
  Generic Type: <Todo>
    Type Structure:
      id: number
      title: string
      completed: boolean
  Parameters:
    Position 0: id: number
    Position 1: title: string
    Position 2: completed: boolean
    Position 3: myTodoDbConn: FabricSqlConnection [FABRIC: FabricSqlConnection]
  Parameter Summary:
    Total Parameters: 4
    Fabric Parameters: 1
      Position 3: myTodoDbConn (FabricSqlConnection)
    Business Parameters: 3
      Position 0: id: number
      Position 1: title: string
      Position 2: completed: boolean
  ✅ Parameter validation: All parameters match generic type structure

*/

udf.func<Todo>("addTodoSpreadParamsFail", async (id: number, title: string, completed: boolean, myTodoDbConn: FabricSqlConnection, extraParam: string) => {
    // Logic to add the todo item to a database or in-memory store
    console.log(`Adding todo: ${title}`);
    return { success: true, message: `Todo '${title}' added successfully!` };

}, [myTodoDbConn]);

/*
Function Registration: "addTodoSpreadParamsFail"
  File: fabric.ts
  Async: true
  Has Data Connections: true
  Return Type: unknown
  Generic Type Argument: <Todo>
  Input Type Structure:
    - id: number
    - title: string
    - completed: boolean
  Delegate Parameters:
    1. Position 0 - id: number
    2. Position 1 - title: string
    3. Position 2 - completed: boolean
    4. Position 3 - myTodoDbConn: FabricSqlConnection (Fabric: FabricSqlConnection)
    5. Position 4 - extraParam: string
  Parameter Classification:
    Fabric Parameters (1): myTodoDbConn@3
    Business Parameters (4): id@0, title@1, completed@2, extraParam@4
  Business Parameters: id: number, title: string, completed: boolean, extraParam: string
  🚨 Parameter Validation ERRORS:
    ❌ Extra parameters not in generic type: extraParam
*/


// 3. Without type, we will look through the request to attempt to match up parameters.
udf.func("getTodo", async (myTodoDbConn: FabricSqlConnection, id: number) : Promise<Todo> => {
    // Logic to retrieve the todo item from a database or in-memory store
    console.log(`Getting todo with id: ${id}`);

    //return myTodoDbConn.sql("SELECT * FROM todos WHERE id = ?", [id]) as Todo;
    return { id, title: "Sample Todo", completed: false };

}, [myTodoDbConn]);
/*
"getTodo" (fabric.ts)
  Async: true, Has Data Connections: true
  Return Type: Promise<Todo>
    Return Type Structure:
      id: number
      title: string
      completed: boolean
  Parameters:
    Position 0: myTodoDbConn: FabricSqlConnection [FABRIC: FabricSqlConnection]
    Position 1: id: number
  Parameter Summary:
    Total Parameters: 2
    Fabric Parameters: 1
      Position 0: myTodoDbConn (FabricSqlConnection)
    Business Parameters: 1
      Position 1: id: number
*/


udf.func("listTodos", async (myTodoDbConn: FabricSqlConnection) : Promise<Todo[]> => {
    // Logic to retrieve all todo items from a database or in-memory store
    console.log(`Listing all todos`);
    // return myTodoDbConn.sql("SELECT * FROM todos") as Todo[];
    return [
        { id: 1, title: "Sample Todo 1", completed: false },
        { id: 2, title: "Sample Todo 2", completed: true }
    ];
}, [myTodoDbConn]);

/*
"listTodos" (fabric.ts)
  Async: true, Has Data Connections: true
  Return Type: Promise<Todo[]>
  Parameters:
    Position 0: myTodoDbConn: FabricSqlConnection [FABRIC: FabricSqlConnection]
  Parameter Summary:
    Total Parameters: 1
    Fabric Parameters: 1
      Position 0: myTodoDbConn (FabricSqlConnection)
    Business Parameters: 0
*/


// Only thing required for Rayfin is to export the type signature of each function
export type FabricFunctionSchema = {
    addTodo: RayfinFunctionSchema<Todo, { success: boolean; message: string }>;
    getTodo: RayfinFunctionSchema<number, Todo>;
    listTodos: RayfinFunctionSchema<undefined, Todo[]>;
}